# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
variables:
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: 'src/MarkEmbling.PostcodesIO/MarkEmbling.PostcodesIO.csproj'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build $(buildConfiguration)'
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: 'pack'
      packagesToPack: 'src/MarkEmbling.PostcodesIO/MarkEmbling.PostcodesIO.csproj'
      versioningScheme: 'off'
